config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'articles/index'
  get "Inicio", to: "articles#index"
  resources :articles
  root 'articles#index'
  get "/articles/new", to: 'articles#new'
  get "/articles/safe", to: 'articles#safe'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :searches
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  def self.search(search)
    if search
      where(["fecha LIKE ?","%#{search}%"])
    else
      all
    end
  end
  def self.searchmax(searchmax)
    if searchmax
      where(["fecha LIKE ?","%#{searchmax}%"])
    else
      all
    end
  end
  def self.searchtitle(searchtitle)
    if searchtitle
      where(["title LIKE ?","%#{searchtitle}%"])
    else
      all
    end
  end
  def self.searchtipo(searchtipo)
    if searchtipo
      where(["tipo_consulta LIKE ?","%#{searchtipo}%"])
    else
      all
    end
  end
  def self.searchcie(searchcie)
    if searchcie
      where(["cie LIKE ?","%#{searchcie}%"])
    else
      all
    end
  end
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true, uniqueness: true
    validates :fecha, presence: true
    validates :body, presence: true

    has_attached_file :cover, styles: { medium: "1280x720", thumb:"800x600" }
    validates_attachment_content_type :cover, content_type: /\Aimage\/.*\Z/

    has_attached_file :documents
    

end

app/models/search.rb
class Search < ApplicationRecord
    def articles
        @articles ||=find_articles
    end

    private

    def find_articles
        articles = Articles.order(:id)
        articles = Articles.where("keywords like ?", "%#{title}%") if keywords.present?
        articles = Articles.where("min_fecha >= ?", min_fecha) if min_fecha.present?
        articles = Articles.where("max_fecha <= ?", max_fecha) if max_fecha.present?
        articles = Articles.where("tipo like ?", tipo) if tipo.present?
        articles = Articles.where("enfermedad like ?", enfermedad) if enfermedad.present?
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    add_flash_types :success, :info
    def index
        @articles = Article.order('fecha DESC')
        if (params[:search].present? && params[:searchmax].present?)
            @articles = @articles.where("fecha >= ?", "#{params[:search]}")
            @articles = @articles.where("fecha <= ?", "#{params[:searchmax]}")
        elsif (params[:search].present?)
            @articles = @articles.where("fecha LIKE ?", "%#{params[:search]}%")
        elsif(params[:searchmax].present?)
            @articles = @articles.where("fecha LIKE ?", "%#{params[:searchmax]}%")
        end
        if params[:searchtitle].present?
            @articles = @articles.where("title LIKE ?", "%#{params[:searchtitle]}%")
        end
        if params[:searchtipo].present?
            @articles = @articles.where("tipo_consulta LIKE ?", "%#{params[:searchtipo]}%")
        end
        if params[:searchcie].present?
            @articles = @articles.where("cie LIKE ?", "%#{params[:searchcie]}%")
        end
    end
    
    def show
        @article = Article.find(params[:id])
    end
    def new
        @article = Article.new
    end
    def create
        @article = Article.new(article_params)
        if @article.save
            redirect_to @article, success: "Guardado con éxito"
        else
            render :new
        end
    end
    def destroy
        @article = Article.find(params[:id])
        @article.destroy
        redirect_to articles_path, success: "Eliminada con éxito"
    end
    def update
        @article = Article.find(params[:id])
        if @article.update(article_params)
            redirect_to @article, success: "Actualizada con éxito"
        else
            render :edit
        end
    end
      
    def edit
        @article = Article.find(params[:id])
    end
    
    private

    def article_params
        params.require(:article).permit(:title,:cover,:documents,:fecha,:body,:tipo_consulta,:cie,:sintomas,:medicacion,:examenes,:diagnostico,:hospital,:doctor)
    end

end

app/controllers/bienvenido_controller.rb
class BienvenidoController < ApplicationController
  def index
  end
end

app/controllers/registros_controller.rb
class RegistrosController < ApplicationController
    def index
        
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
    def new
        @search = Search.new
    end

    def create
        @search = Search.create!(searches_params)
        redirect_to @search
    end

    def show
        @search = Search.find(params[:id])
    end
    
    private

    def searches_params
        params.require(:search).permit(:keywords)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bienvenido_helper.rb
module BienvenidoHelper
end

app/helpers/registros_helper.rb
module RegistrosHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/articles/_flash_messages.html.erb
<% flash.each do |name, msg| %>
    <div class="alert alert-<%= name %>">
        <%= msg %>
    </div>
<% end %>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
    <% @article.errors.full_messages.each do |message| %>
        <div class="be-blue white top-space">
        * <%= message %>
        </div>
    <%end%>
    <div class="field">
        <%= f.text_field :title, placeholder: "Titulo", class:"form-control" %>
    </div>
    <div class="field">
        Imagen: <%= f.file_field :cover %>
    </div>
    <div class="field">
        Documento: <%= f.file_field :documents %>
    </div>
    <div class="field">
        <%= f.text_field :fecha, placeholder: "Fecha (AAAA-MM-DD)", class:"form-control" %>
    </div>
    <div class="field">
        <%= f.text_area :body, placeholder: "Escribe aquí la consulta", style:"height:250px", class:"form-control" %>
    </div>
    <div class="field">
        <%= f.text_field :tipo_consulta, placeholder: "Tipo de consulta", class:"form-control" %>
    </div>
    <div class="field">
        <%= f.text_field :cie, placeholder: "CIE-10", class:"form-control" %>
    </div>
    <div class="field">
        <%= f.text_area :sintomas, placeholder: "Síntomas", style:"height:100px", class:"form-control" %>
    </div>
    <div class="field">
        <%= f.text_area :medicacion, placeholder: "Medicación Prescrita", style:"height:50px", class:"form-control" %>
    </div>
    <div class="field">
        <%= f.text_area :examenes, placeholder: "Exámenes Solicitados", style:"height:100px", class:"form-control" %>
    </div>
    <div class="field">
        <%= f.text_area :diagnostico, placeholder: "Diagnóstico", style:"height:100px", class:"form-control" %>
    </div>
    <div class="field">
        <%= f.text_field :hospital, placeholder: "Hospital", class:"form-control" %>
    </div>
    <div class="field">
        <%= f.text_field :doctor, placeholder: "Doctor", class:"form-control" %>
    </div>
    <div class="field">
        <%= f.submit "Guardar", class:"btn be-blue", data: { confirm: '¿Desea guardar el regstro?' } %>
    </div>
<%end%>

app/views/articles/edit.html.erb
<h1>Editar consulta</h1>
<%= render "form" %>
</div>

app/views/articles/index.html.erb
<% if user_signed_in? %>
    <h1>Bienvenido a tu Historial Médico <%= current_user.email %></h1>
<% else %>
    <h1>Bienvenido, ingresa a tu cuenta</h1>
<%end%>
<%= form_tag articles_path, :method => 'get' do %>
    <%= label_tag "Fecha"%> -
    <%= text_field_tag :search, params[:search] %>
    <%= label_tag "Fecha Max"%> -
    <%= text_field_tag :searchmax, params[:searchmax] %>
    <%= label_tag "Titulo"%> -
    <%= text_field_tag :searchtitle, params[:searchtitle] %>
    <%= label_tag "Tipo de Consulta"%> -
    <%= text_field_tag :searchtipo, params[:searchtipo] %>
    <%= label_tag "CIE"%> -
    <%= text_field_tag :searchcie, params[:searchcie] %>
    <%= submit_tag "Buscar" %>
<% end %>
<h1>Consultas</h1>

<table>
    <thead>
        <tr>
            <th>Título</th>
            <th>Fecha</th>
            <th>Tipo de Consulta</th>
            <th>CIE-10</th>
            <th colspan="4"></th>
        </tr>
    </thead>

    <tbody>
        <% @articles.each do |article| %>
            <tr>
                <td><%= link_to article.title, article %></td>
                <td><%= article.fecha %></td>
                <td><%= article.tipo_consulta %></td>
                <td><%= article.cie %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/articles/new.html.erb
<h1>Crear consulta</h1>
<%= form_for(@article) do |f| %>
    <% @article.errors.full_messages.each do |message| %>
        <div class="be-blue white top-space">
        * <%= message %>
        </div>
    <%end%>
    <div class="field">
        <%= f.text_field :title, placeholder: "Titulo", class:"form-control" %>
    </div>
    <div class="field">
        Imagen: <%= f.file_field :cover %>
    </div>
    <div class="field">
        Documento: <%= f.file_field :documents %>
    </div>
    <div class="field">
        <%= f.text_field :fecha, placeholder: "Fecha (AAAA-MM-DD)", class:"form-control" %>
    </div>
    <div class="field">
        <%= f.text_area :body, placeholder: "Escribe aquí la consulta", style:"height:150px", class:"form-control" %>
    </div>
    <div class="field">
        <%= f.text_field :tipo_consulta, placeholder: "Tipo de consulta", class:"form-control" %>
    </div>
    <div class="field">
        <%= f.text_field :cie, placeholder: "CIE-10", class:"form-control" %>
    </div>
    <div class="field">
        <%= f.text_area :sintomas, placeholder: "Síntomas", style:"height:100px", class:"form-control" %>
    </div>
    <div class="field">
        <%= f.text_area :medicacion, placeholder: "Medicación Prescrita", style:"height:50px", class:"form-control" %>
    </div>
    <div class="field">
        <%= f.text_area :examenes, placeholder: "Exámenes Solicitados", style:"height:100px", class:"form-control" %>
    </div>
    <div class="field">
        <%= f.text_area :diagnostico, placeholder: "Diagnóstico", style:"height:100px", class:"form-control" %>
    </div>
    <div class="field">
        <%= f.text_field :hospital, placeholder: "Hospital", class:"form-control" %>
    </div>
    <div class="field">
        <%= f.text_field :doctor, placeholder: "Doctor", class:"form-control" %>
    </div>
    <div class="field">
        <%= f.submit "Guardar", class:"btn be-blue", data: { confirm: '¿Desea guardar el regstro?' } %>
    </div>
<%end%>

app/views/articles/show.html.erb
<h1>
<%= label_tag "Título:"%><%= @article.title %>
</h1>
<% if @article.cover.present? %>
<div class="field">
    <%= image_tag @article.cover.url() %> 
</div>
<div><%= link_to "Imagen", @article.cover.url() %></div>
<%end%>
<% if @article.documents.present? %>
<div><%= link_to "Documento", @article.documents.url() %></div>
<%end%>
<div>
<%= label_tag "Fecha:"%><%= @article.fecha %>
</div>
<div>
<%= label_tag "Consulta:"%><%= @article.body %>
</div>
<% if @article.tipo_consulta.present? %>
<div>
<%= label_tag "Tipo de Consulta:"%><%= @article.tipo_consulta %>
</div>
<%end%>
<% if @article.cie.present? %>
<div>
<%= label_tag "CIE-10:"%><%= @article.cie %>
</div>
<%end%>
<% if @article.sintomas.present? %>
<div>
<%= label_tag "Síntomas:"%><%= @article.sintomas %>
</div>
<%end%>
<% if @article.medicacion.present? %>
<div>
<%= label_tag "Medicación Prescrita:"%><%= @article.medicacion %>
</div>
<%end%>
<% if @article.examenes.present? %>
<div>
<%= label_tag "Exámenes Solicitados:"%><%= @article.examenes %>
</div>
<%end%>
<% if @article.diagnostico.present? %>
<div>
<%= label_tag "Diagnóstico:"%><%= @article.diagnostico %>
</div>
<%end%>
<% if @article.hospital.present? %>
<div>
<%= label_tag "Hospital:"%><%= @article.hospital %>
</div>
<%end%>
<% if @article.doctor.present? %>
<div>
<%= label_tag "Doctor:"%><%= @article.doctor %>
</div>
<%end%>
<%= link_to "Editar", edit_article_path(@article),class:"yellow", data: { confirm: '¿Seguro que desea editar el registro?' } %>
<%= link_to "Eliminar", @article, class:"red", method: :delete, data: { confirm: '¿Seguro que desea eliminar el registro?' } %>
</div>

app/views/bienvenido/index.html.erb
<h1>Hola mundo</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href=<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet"> 
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
      <header>
        <nav class="be-blue white large-padding">
          <ul class="no-list row center-xs middle-xs">
            <li class="col-md">
              <h1 class="no-margin" id="logo">Historial Medico</h1>
            </li>
            <li class="col-md">
              <%= link_to "Inicio", root_path %>
            </li>
            <li class="col-md">
              <%= link_to "Registrar", '/articles/new'%>
            </li>
            <% if user_signed_in? %>
              <li class="col-md">
                <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete %>
              </li>
            <%else%>
              <li class="col-md">
                <%= link_to "Iniciar sesión", new_user_session_path %>
              </li>
              <li class="col-md">
                <%= link_to "Crear cuenta", new_user_registration_path %>
              </li>
            <% end %>
          </ul>
        </nav>
      </header>
      <% flash.each do |name, msg| %>
        <div class='alert alert-<%= name %>'>
          <%= msg %>
        </div>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/searches/new.html.erb
<h1>Búsqueda de Consultas</h1>

<%= form_for @search do |f| %>
    <div class="field">
        <%= f.label :keywords %><br />
        <%= f.text_field :keywords %>
    </div>
    <div class="field">
        <%= f.label :min_fecha, "Rango de Fechas" %><br />
        <%= f.text_field :min_fecha %>
        <%= f.text_field :max_fecha %>
    </div>
    <div class="field">
        <%= f.label :Tipo_de_Consulta %><br />
        <%= f.text_field :tipo %>
    </div>
   <div class="field">
        <%= f.label :Cie_10 %><br />
        <%= f.text_field :enfermedad %>
    </div>
    <div class="actions"><%= f.submit "Buscar" %></div>
<% end %>

app/views/searches/show.html.erb
<h1>Resultados de Búsqueda</h1>

<%= render @search.articles %>